### ISSUE TITLE
Add readme to theme toggle template

### ISSUE THREAD

**Issue by mudit023** [mudit023/templates#10]
Add a readme for [Theme Toggle](https://github.com/mudit023/templates/tree/main/theme-toggle) template.

**You can take help from this [example](https://github.com/mudit023/templates/blob/main/stats-card-component/README.md)**

**Comment by Programing-School** [comment]
Ok

**Comment by mudit023** [comment]
> Ok

The screenshots are still not visible

**Comment by Programing-School** [comment]
Yes, I will create a full pull request because i am working on other template

> > Ok
> 
> The screenshots are still not visible

**Comment by mudit023** [comment]
> Yes, I will create a full pull request because i am working on other template
okay

**Comment by Programing-School** [comment]
Hey @mudit023 

Accept the Pull request

**Comment by imRajAryan09** [comment]
I'll do it

**Comment by Programing-School** [comment]
> I'll do it

I do it

**Comment by Programing-School** [comment]
@mudit023 Please Come to chat on slack

**Comment by Programing-School** [comment]
Close This Issue
