### ISSUE TITLE
Creating a SSB(service selection Board ) Screening Test hosting website

### ISSUE THREAD

**Issue by Akayush-17** [mudit023/templates#102]
## Have an idea for a new HTML, CSS, or JS template? Describe it here.
NDA/Tes or another Selection process in joining defense force requires Clearing Screening Test. This website will host all test which are there in screening test. 
## List all the functionalities/ animations it should have(if any)
-Image slider image stays on screen for 30s meanwhile student has to write his response by typing in text area.
-OIR questions with limited time.
-Student view on the photograph show.

**Comment by mudit023** [comment]
Hey, it's good to see your zeal to contribute to this repo. However, this project is just for reusable HTML, CSS, JS, templates.
