### ISSUE TITLE
Want to add a music player template.

### ISSUE THREAD

**Issue by DeveloperAshish8** [mudit023/templates#105]
## Have an idea for a new HTML, CSS, or JS template? Describe it here.
Want to add an awesome music player template.

## Add a design file/ Screenshot of the template you want
![Screenshot (10)](https://user-images.githubusercontent.com/90233808/194710182-2b7fe5c9-866b-4d22-a539-2c7a7ff5fa66.png)

## List all the functionalities/ animations it should have(if any)
- Can add songs thumbnails.
- Can play songs along with scrolling

**Comment by DeveloperAshish8** [comment]
Please assign me this issue under hacktoberfest .

**Comment by Susaksham** [comment]
> Please assign me this issue under hacktoberfest .

You are good to go
