### ISSUE TITLE
Addding Glassmorphism Loader

### ISSUE THREAD

**Issue by yashkondewar** [mudit023/templates#116]
## Have an idea for a new HTML, CSS, or JS template? Describe it here.
I made an animated Glassmorphism loader.

## Add a design file/ Screenshot of the template you want

https://user-images.githubusercontent.com/98695632/195987229-a856e5e1-ddcb-4d9d-9ea5-2a0773548a37.mp4

**Comment by Susaksham** [comment]
Why have you placed this blur element in the center of the page

> ## Have an idea for a new HTML, CSS, or JS template? Describe it here.
> I made an animated Glassmorphism loader.
> 
> ## Add a design file/ Screenshot of the template you want
>  Glassmorphism-loader.mp4

Why have you placed this blurred element in the center of the page.

**Comment by Susaksham** [comment]
> ## Have an idea for a new HTML, CSS, or JS template? Describe it here.
> I made an animated Glassmorphism loader.
> 
> ## Add a design file/ Screenshot of the template you want
>  Glassmorphism-loader.mp4

Improve the UI and then send the screenshot.

**Comment by yashkondewar** [comment]
> > ## Have an idea for a new HTML, CSS, or JS template? Describe it here.
> > I made an animated Glassmorphism loader.
> > ## Add a design file/ Screenshot of the template you want
> > Glassmorphism-loader.mp4
> 
> Improve the UI and then send the screenshot.

![Screenshot (2432)](https://user-images.githubusercontent.com/98695632/196062050-893b0c94-3637-4f37-b51a-6b1db25cdf5d.png)


An element placed over there is a bucket like structure.

**Comment by mudit023** [comment]
You can a simple CSS loader, no need to make use of glassmorphism.
@yashkondewar

**Comment by yashkondewar** [comment]
> You can add a simple CSS loader, no need to make use of glassmorphism. @yashkondewar


https://user-images.githubusercontent.com/98695632/196740264-361ff775-c9b0-443f-9ea2-a3995a1cc32a.mp4

Is this good??

**Comment by yashkondewar** [comment]
@mudit023

**Comment by mudit023** [comment]
This looks good. You can contribute this.
