### ISSUE TITLE
Animated profile card

### ISSUE THREAD

**Issue by hardikmishra018** [mudit023/templates#124]
## Add a design file/ Screenshot of the template you want
![screenshot](https://user-images.githubusercontent.com/86034284/197523223-8a855dea-a402-4bf2-9fe9-91f59347060b.PNG)
![screenshot-active](https://user-images.githubusercontent.com/86034284/197523233-ecf88ac0-1be2-40fc-8a09-9066d6453f40.PNG)

## List all the functionalities/ animations it should have(if any)
-
-
-

**Comment by mudit023** [comment]
Looks good! Good to go.
