### ISSUE TITLE
Screenshots/GIf not visible of 3D flip card

### ISSUE THREAD

**Issue by mudit023** [mudit023/templates#49]
Screenshots are not visible in the [3D flip card README.md](https://github.com/mudit023/templates/blob/main/3D%20Flip%20Card%20on%20Hover%20-%20Programing-School/README.md)
They are added in the template [folder](https://github.com/mudit023/templates/tree/main/3D%20Flip%20Card%20on%20Hover%20-%20Programing-School).

**Comment by Programing-School** [comment]
Please if the issue is for a problem of my templates please mention me

**Comment by Programing-School** [comment]
And Assign it to me

**Comment by mudit023** [comment]
If you want to solve it, you can.

**Comment by Programing-School** [comment]
> If you want to solve it, you can.

Approve the pull request to create another

**Comment by Programing-School** [comment]
I solve it

**Comment by Programing-School** [comment]
Accept The Pull request and close this Issue

**Comment by mudit023** [comment]
Can you try to add a GIF instead of a screenshot because your template contains animation

**Comment by Programing-School** [comment]
Ok, I will try

**Comment by Programing-School** [comment]
> Can you try to add a GIF instead of a screenshot because your template contains animation

Done

**Comment by mudit023** [comment]
Merged
