### ISSUE TITLE
Website Build

### ISSUE THREAD

**Issue by Rafat97** [mudit023/templates#71]
Hi, 

Have u any plan to create a  static website?
This website will preview all the templates.   

Also, can you checkout this repo, Because, there is a possibility to copy the templates. Make sure that there is no copy from open source template. 

https://github.com/learning-zone/website-templates

**Comment by mudit023** [comment]
Yeah, I'm thinking of creating a website.

**Comment by mudit023** [comment]
Haven't thought about this design yet.

**Comment by Rafat97** [comment]
> > Have you any design/page layout in your head ?
> 
> Do you have anything in mind? We can discuss it.

Sorry for the late response. 

I think, we can make- 

- [ ] A Landing Page [ where showcase all the templates ]
- [ ] Single Page for each of the templates.

You can checkout this web layout. We can take inspiration form this web page. 
https://codepen.io/FlorinPop17/full/VwYWMOa

@mudit023  what's your opinion ?

**Comment by Programming-School-Pro-Coding** [comment]
> > > Have you any design/page layout in your head ?
> > 
> > 
> > Do you have anything in mind? We can discuss it.
> 
> Sorry for the late response.
> 
> I think, we can make-
> 
> * [ ]  A Landing Page ( where showcase all the templates )
> * [ ]  Single Page for each of the templates.
> 
> You can checkout this web layout. We can take inspiration form this web page.
> 
> https://codepen.io/FlorinPop17/full/VwYWMOa https://www.reactplay.io/
> 
> @mudit023 what's your opinion ?

Hi Sir

Very Amazing Suggestions

React Play is very amazing I worked in it and i understand its structure

In my opinion i choose react play if you are wanting to use it i will work on this

**Comment by mudit023** [comment]
> > > Have you any design/page layout in your head ?
> > 
> > 
> > Do you have anything in mind? We can discuss it.
> 
> Sorry for the late response.
> 
> I think, we can make-
> 
> * [ ]  A Landing Page ( where showcase all the templates )
> * [ ]  Single Page for each of the templates.
> 
> You can checkout this web layout. We can take inspiration form this web page.
> 
> https://codepen.io/FlorinPop17/full/VwYWMOa https://www.reactplay.io/
> 
> @mudit023 what's your opinion ?

Sounds good! Let's execute it. Join our slack channel for further discussions.

**Comment by Programming-School-Pro-Coding** [comment]
> > > > Have you any design/page layout in your head ?
> > > 
> > > 
> > > Do you have anything in mind? We can discuss it.
> > 
> > 
> > Sorry for the late response.
> > I think, we can make-
> > 
> > * [ ]   A Landing Page ( where showcase all the templates )
> > * [ ]   Single Page for each of the templates.
> > 
> > You can checkout this web layout. We can take inspiration form this web page.
> > https://codepen.io/FlorinPop17/full/VwYWMOa https://www.reactplay.io/
> > @mudit023 what's your opinion ?
> 
> Sounds good! Let's execute it. Join our slack channel for further discussions.

Please your slack channel please i removed slack from the browser and install it on my computer

**Comment by mudit023** [comment]
**Slack Channel:** https://join.slack.com/t/opensourceden/shared_invite/zt-1a8woq4f8-jKoPW28x2qMrgTqQfItlHw
