### ISSUE TITLE
Changes in Amazing Animated Login Form

### ISSUE THREAD

**Issue by Safirangi** [mudit023/templates#78]
#### Changes needed in [Amazing Animated Login Form](https://github.com/mudit023/templates/tree/main/Amazing%20Animated%20Login%20Form)

- [ ] use of CSS Variables
- [ ] comments in HTML & JavaScript code
- [ ] editing README.md file

**Comment by mudit023** [comment]
You can work on this issue.

**Comment by mudit023** [comment]
Add screenshots also in the readme.

**Comment by Safirangi** [comment]
> Add screenshots also in the readme.

Screenshots of the code you mean?

**Comment by mudit023** [comment]
> > Add screenshots also in the readme.
> 
> Screenshots of the code you mean?

No, add screenshots of the template created(the output) in the readme file.

**Comment by mudit023** [comment]
Do this and I'll merge the PR.

**Comment by Safirangi** [comment]
I think the README file already has the output screenshots

**Comment by mudit023** [comment]
Yeah! Just saw.

**Comment by Safirangi** [comment]
Thanks for guiding me! 😄
