### ISSUE TITLE
Correct the active state in Navbar

### ISSUE THREAD

**Issue by imRajAryan09** [mudit023/templates#8]
When I hover over the elements of the navbar the Home stays active. ![Repo Link](https://github.com/mudit023/templates/tree/main/theme-toggle) <br>
![WhatsApp Image 2022-04-11 at 5 06 20 PM](https://user-images.githubusercontent.com/81006469/162731623-0c1cf448-dbd3-4250-8f8c-484e70cda405.jpeg)
.

**Comment by Programing-School** [comment]
Hi,

You work with react and This repo is for Html CSS Only

**Comment by Programing-School** [comment]
I don't understand what do you mean with active state in navbar

**Comment by mudit023** [comment]
> I don't understand what do you mean with active state in navbar

when you hover over other links the animation of the purple line on the left of the link should change from home to the link you are hovering over.

**Comment by Programing-School** [comment]
> > I don't understand what do you mean with active state in navbar
> 
> when you hover over other links the animation of the purple line on the left of the link should change from home to the link you are hovering over.
Ok 👌

**Comment by Programing-School** [comment]
> > I don't understand what do you mean with active state in navbar
> 
> when you hover over other links the animation of the purple line on the left of the link should change from home to the link you are hovering over.

Please Explain why you assign me

**Comment by hs-07** [comment]
hey buddy @mudit023 ... assign me the issue... I understood what u are trying explain and wanted to work over it.

**Comment by Programing-School** [comment]
> hey buddy @mudit023 ... assign me the issue... I understood what u are trying explain and wanted to work over it.

I understand too and i was finished the issue but @mudit023 is offline so i am waiting to accept my pull request

Note I am from contributers

**Comment by hs-07** [comment]
okkk... no issues @Programing-School

**Comment by mudit023** [comment]
> hey buddy @mudit023 ... assign me the issue... I understood what u are trying explain and wanted to work over it.

Thanks for showing your interest. If you want you can contribute to other issues or you can contribute a new template.

**Comment by Programing-School** [comment]
Close this issue because the problem solved
