### ISSUE TITLE
Adding Profile Card

### ISSUE THREAD

**Issue by yashkondewar** [mudit023/templates#80]
## Have an idea for a new HTML, CSS, or JS template? Describe it here.
I have made a profile card.

## Add a design file/ Screenshot of the template you want
https://user-images.githubusercontent.com/98695632/193603384-c143df99-1942-42c2-9648-91511d0b9c99.mp4

**Comment by mudit023** [comment]
Looks awesome! You are good to go.

**Comment by mudit023** [comment]
#81 Kindly follow our [template guidelines](https://github.com/mudit023/templates/blob/main/TEMPLATE_GUIDELINES.md).

**Comment by mudit023** [comment]
PR merged.
