### ISSUE TITLE
Payment Gateway template

### ISSUE THREAD

**Issue by Akanksha-Sen** [mudit023/templates#86]
## Have an idea for a new HTML, CSS, or JS template? Describe it here.
Payment gateway template

## List all the functionalities/ animations it should have(if any)
-
-
-

**Comment by Susaksham** [comment]
You are good to go , Please follow our templates guidelines [template guidelines](https://github.com/mudit023/templates/blob/main/TEMPLATE_GUIDELINES.md).

**Comment by Akanksha-Sen** [comment]
Hey, I couldn't understand how and where the css variables are to be added. If you don't mind, could you please help?

**Comment by mudit023** [comment]
Check this [example](https://github.com/mudit023/templates/blob/main/Profile-Card-3/style.css). And let me know if you still face any problems.

**Comment by mudit023** [comment]
Hey @Akanksha-Sen you working on it? If you are facing any problem kindly let me know.
