### ISSUE TITLE
Changes in animated-newsletter

### ISSUE THREAD

**Issue by Safirangi** [mudit023/templates#87]
#### Changes proposed for the [animated-newsletter](https://github.com/mudit023/templates/tree/main/animated-newsletter)

- [ ] use of CSS Variables
- [ ] add comments in HTML code
- [ ] add comments in JavaScript code

**Comment by mudit023** [comment]
You are good to go.

**Comment by mudit023** [comment]
And please mention the issue in your PR. So that the issues will get closed when I merge your PR.
