### ISSUE TITLE
Template not described well

### ISSUE THREAD

**Issue by mudit023** [mudit023/templates#91]
[This template](https://github.com/mudit023/templates/tree/main/Drag%20and%20Drop) is not described well in its [Readme file](https://github.com/mudit023/templates/blob/main/Drag%20and%20Drop/README.md).

### What you have to do:
- [ ] Use the template on your local machine.
- [ ] Check what it does
- [ ] And then improve the Readme file accordingly.
- [ ] Make use of gifs in the readme file for better clarity.

**Comment by sunkusaarthak** [comment]
Assign this to me if not assigned to anyone.

**Comment by shivanshi-s** [comment]
Hi, I would like to give this a try as well!

**Comment by Susaksham** [comment]
> Hi, I would like to give this a try as well!

You can work on any other issue as  this issue already assigned to someone else

**Comment by sunkusaarthak** [comment]
Can you please check the updated readme file.
