### ISSUE TITLE
Image Gallery

### ISSUE THREAD

**Issue by hamzailyas237** [mudit023/templates#92]
Image Gallery
I want to create an image gallery template, for the purpose of Hactoberfest. Please assign it.
Thank you.

**Comment by Susaksham** [comment]
> Image Gallery I want to create an image gallery template, for the purpose of Hactoberfest. Please assign it. Thank you.

Please add the screenshot of the gallery template , then you are good to go

**Comment by hamzailyas237** [comment]
@Susaksham  ![image](https://user-images.githubusercontent.com/65035919/194363841-849d4a6b-eb57-4356-af78-e1dbfbe201f0.png)

**Comment by hamzailyas237** [comment]
Do you want open each image on full page or I can open below these images

**Comment by Programming-School-Pro-Coding** [comment]
> Do you want open each image on full page or I can open below these images

Anything you want guys then send i video of the app

**Comment by hamzailyas237** [comment]
@Programming-School-Pro-Coding When i click on it will opens below
![image](https://user-images.githubusercontent.com/65035919/194365784-32efa4be-97d5-4e18-8b9a-d4bac79f0e1e.png)

**Comment by Programming-School-Pro-Coding** [comment]
> Is it okay or do want to open it new tab

No, It's Okay

**Comment by hamzailyas237** [comment]
Please add a hactoberfest label.

**Comment by mudit023** [comment]
#94 fix few issues in the PR @hamzailyas237
