### ISSUE TITLE
Image-Carousel

### ISSUE THREAD

**Issue by AbhiMishra-Now** [mudit023/templates#96]
created using html, css, javascript.

![Screenshot (787)](https://user-images.githubusercontent.com/79761277/194500473-3efbe5eb-547b-4227-8b0e-e7997a825ab8.png)
![Screenshot (786)](https://user-images.githubusercontent.com/79761277/194500506-601d5540-5928-4842-8a58-3be8a3da4ba1.png)

it'll have next and  previous buttons but it can automatically slide

**Comment by Susaksham** [comment]
You are good to go

**Comment by Susaksham** [comment]
> created using html, css, javascript.
> 
> ![Screenshot (787)](https://user-images.githubusercontent.com/79761277/194500473-3efbe5eb-547b-4227-8b0e-e7997a825ab8.png) ![Screenshot (786)](https://user-images.githubusercontent.com/79761277/194500506-601d5540-5928-4842-8a58-3be8a3da4ba1.png)
> 
> it'll have next and previous buttons but it can automatically slide

You are good to go

**Comment by mudit023** [comment]
Hey @AbhiMishra-Now please add a small video of the working of your carousel in your template readme file.

**Comment by AbhiMishra-Now** [comment]
> Hey @AbhiMishra-Now please add a small video of the working of your carousel in your template readme file.

yes I've created a demo folder in which I have added a gif of my work
